

services:

  # ─────────────────────────────────────────
  # CONFIG SERVER
  # ─────────────────────────────────────────

  config-server:
    build:
      context: ./backend/config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - hms-microservices-network
    environment:
      - SPRING_PROFILES_ACTIVE=native
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────────────────
  # DISCOVERY SERVICE (EUREKA)
  # ─────────────────────────────────────────

  eureka-server:
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────────────────
  # AUTH SERVICE
  # ─────────────────────────────────────────

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─────────────────────────────────────────
  # PATIENT SERVICE
  # ─────────────────────────────────────────

  patient-service:
    build:
      context: ./backend/patient-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=${PATIENTDB_URL}
      - SPRING_DATASOURCE_USERNAME=${PATIENTDB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PATIENTDB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  #DOCTOR-SERVICE
  doctor-service:
    build:
      context: ./backend/doctor-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=${DOCTORDB_URL}
      - SPRING_DATASOURCE_USERNAME=${DOCTORDB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DOCTORDB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5    


   #APPOINTMENT-SERVICE
  appointment-service:
    build:
      context: ./backend/appointment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=${APPOINTMENTDB_URL}
      - SPRING_DATASOURCE_USERNAME=${APPOINTMENTDB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${APPOINTMENTDB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5   

  # ─────────────────────────────────────────
  # API GATEWAY
  # ─────────────────────────────────────────

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

    # ─────────────────────────────────────────
    # PRESCRIPTION SERVICE
    # ───────────────────────────────────────── 

  prescription-service:
    build:
      context: ./backend/prescription-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - hms-microservices-network
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=${PRESCRIPTIONDB_URL}
      - SPRING_DATASOURCE_USERNAME=${PRESCRIPTIONDB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${PRESCRIPTIONDB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5 

# ─────────────────────────────────────────
# NETWORKS
# ─────────────────────────────────────────

networks:
  hms-microservices-network:
    driver: bridge