apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: healthcare-system
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_ME"
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
  EUREKA_USERNAME: "REPLACE_ME"
  EUREKA_PASSWORD: "REPLACE_ME"
  MAIL_USERNAME: "REPLACE_ME"
  MAIL_PASSWORD: "REPLACE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-patient-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-doctor-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-appointment-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-prescription-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-notification-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-billing-secret
  namespace: healthcare-system
type: Opaque
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"
  POSTGRES_DB: "healthcare"
