package com.healthcare.notification.entity;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_REMINDER,
    PRESCRIPTION_ISSUED,
    PRESCRIPTION_EXPIRY,
    BILLING_INVOICE,
    PAYMENT_RECEIVED,
    GENERAL
}
